name:                conjecture
version:             1.0.0.0
license:             BSD3
author:              "GarkGarcia"
maintainer:          "thiago.brevidelli.garcia@gmail.com"
copyright:           "2019 GarkGarcia"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: This program is a simple test for a little conjecture of mine.

dependencies:
  - base >= 4.7 && < 5
  - clock == 0.7.2

library:
  source-dirs: src

executables:
  conjecture-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O
    dependencies:
      - conjecture
      - clock == 0.7.2

tests:
  conjecture-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - conjecture
